// controllers/patient_controller.go
package controllers

import (
	"clinic-app/models"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

func CreatePatient(c *fiber.Ctx) error {
	db := c.Locals("db").(*gorm.DB)

	// Check if user exists in context
	user, ok := c.Locals("user").(map[string]interface{})
	if !ok {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{"error": "User not authenticated"})
	}

	var patient models.Patient
	if err := c.BodyParser(&patient); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "Invalid input"})
	}

	// Get user ID and validate it exists
	userIDStr, ok := user["id"].(string)
	if !ok {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": "Invalid user ID format"})
	}

	userID, err := uuid.Parse(userIDStr)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": "Invalid UUID format"})
	}

	// Check if user ID exists in the database
	var count int64
	db.Table("users").Where("id = ?", userID).Count(&count)
	if count == 0 {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": "User ID does not exist"})
	}

	// UUID will be automatically generated by the BeforeCreate hook
	patient.CreatedBy = userID
	patient.UpdatedBy = userID

	if err := db.Create(&patient).Error; err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"error":   "Could not create patient",
			"details": err.Error(),
		})
	}

	return c.JSON(patient)
}

func GetPatients(c *fiber.Ctx) error {
	db := c.Locals("db").(*gorm.DB)
	var patients []models.Patient
	db.Find(&patients)
	return c.JSON(patients)
}

func GetPatientByID(c *fiber.Ctx) error {
	db := c.Locals("db").(*gorm.DB)
	id := c.Params("id")

	// Parse the UUID from string
	patientID, err := uuid.Parse(id)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "Invalid patient ID format"})
	}

	var patient models.Patient
	if err := db.First(&patient, "id = ?", patientID).Error; err != nil {
		return c.Status(fiber.StatusNotFound).JSON(fiber.Map{"error": "Patient not found"})
	}
	return c.JSON(patient)
}

func UpdatePatient(c *fiber.Ctx) error {
	db := c.Locals("db").(*gorm.DB)
	user := c.Locals("user").(map[string]interface{})

	id := c.Params("id")

	// Parse the UUID from string
	patientID, err := uuid.Parse(id)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "Invalid patient ID format"})
	}

	var patient models.Patient
	if err := db.First(&patient, "id = ?", patientID).Error; err != nil {
		return c.Status(fiber.StatusNotFound).JSON(fiber.Map{"error": "Patient not found"})
	}

	// Save the current ID because body parsing will override it
	currentID := patient.ID

	if err := c.BodyParser(&patient); err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "Invalid input"})
	}

	// Ensure ID doesn't change
	patient.ID = currentID

	// Update the updated_by field
	userIDStr, ok := user["id"].(string)
	if !ok {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": "Invalid user ID format"})
	}

	userID, err := uuid.Parse(userIDStr)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{"error": "Invalid UUID format"})
	}
	if ok {
		patient.UpdatedBy = userID
	}

	db.Save(&patient)
	return c.JSON(patient)
}

func DeletePatient(c *fiber.Ctx) error {
	db := c.Locals("db").(*gorm.DB)

	id := c.Params("id")

	// Parse the UUID from string
	patientID, err := uuid.Parse(id)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "Invalid patient ID format"})
	}

	var patient models.Patient
	if err := db.First(&patient, "id = ?", patientID).Error; err != nil {
		return c.Status(fiber.StatusNotFound).JSON(fiber.Map{"error": "Patient not found"})
	}
	db.Delete(&patient)
	return c.Status(fiber.StatusOK).JSON(fiber.Map{"MESSAGE": "Patient deleted successfully"})
}
